# Jekyll configuration
name: NenoLoje.com
url: https://nenoalm.github.io/research-github-pages
markdown: GFM
timezone: Europe/Berlin
lang: de-DE
#title: null # to remove the header
description: Hi, my name is Neno Loje and this is my web page.

theme: jekyll-theme-primer # default theme for GitHub Pages
